# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:559.0.0-emulators@sha256:8ff6edb39f20ac083a787c1bf41f2215522c9aac9f2743820acbea2bd63d7d47
RUN apt-get update -y && apt-get install -y netcat-traditional
